export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const ADD_SHOWN_QUESTION = 'ADD_SHOWN_QUESTION';
export const REMOVE_SHOWN_QUESTION = 'REMOVE_SHOWN_QUESTION';
export const RESET_SHOWN_QUESTIONS = 'RESET_SHOWN_QUESTIONS';

export const ADD_ANSWER = 'ADD_ANSWER';
export const SKIP_ANSWER = 'SKIP_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';
export const CLEAN_ANSWERS = 'CLEAN_ANSWERS';
export const RESET_ANSWERS = 'RESET_ANSWERS';

export const SET_CHOICES = 'SET_CHOICES';
export const RESET_ALL_CHOICES = 'RESET_ALL_CHOICES';
export const SET_SELECTED_CHOICES = 'SET_SELECTED_CHOICES';

export const TEXT_CHANGE = 'TEXT_CHANGE';
export const TEXT_SUBMIT = 'TEXT_SUBMIT';
export const TEXT_RESET = 'TEXT_RESET';

export const SET_ALL_ANSWERED = 'SET_ALL_ANSWERED';
export const SET_SHOW_ERROR = 'SET_SHOW_ERROR';
export const SET_ERROR_MSG = 'SET_ERROR_MSG';

export const SET_CATEGORY = "SET_CATEGORY";
export const SET_PLACE = "SET_PLACE";

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const SET_QUESTIONS_LOADING_STATE = 'SET_QUESTIONS_LOADING_STATE';
export const SET_CHOICES_LOADING_STATE = 'SET_CHOICES_LOADING_STATE';
export const SET_CATEGORY_LOADING_STATE = 'SET_CATEGORY_LOADING_STATE';
export const SET_PLACE_LOADING_STATE = 'SET_PLACE_LOADING_STATE';
export const RESET_LOADING_STATE = 'RESET_LOADING_STATE';
